### PR TITLE
Typos and Fixes

### PR DESCRIPTION
**Pull request by JeremyEllingham**
This is a collection of typos and fixes that I have encountered, up to "Freezing of Merchant accounts".  One common issue is the use of the singular verb conjugations instead of plural in the right spots, a very easy thing to overlook especially for non native English speakers.

There's a few other mistakes, and a couple of slight improvements that I recommend, they should all be fairly self explanatory.

I'll do a follow up PR with changes for the rest of the book, or this PR can stay open until I've finished if that is preferred.

### CODE REVIEW

**Comment by treeman** [comment]
Well, this is amazing. <3

I'll leave the PR open until you're done, just leave a comment when you're happy with it and I'll merge it.

**Comment by JeremyEllingham** [comment]
I haven't forgotten this, I am working on it, just been really busy recently and there's a lot to read through and tweak.  It's underway though.

**Comment by treeman** [comment]
No worries, thank you.

**Comment by JeremyEllingham** [comment]
@treeman Done.  Proofread the whole book.  Maybe I missed something here or there but in general I think these changes catch a lot of small errors.

**Comment by treeman** [comment]
Dude. This is *amazing*. How could I ever make this up to you?

**Comment by JeremyEllingham** [comment]
Just keep making BCH great, and come back on for an episode of the podcast any time you like.

**Pull request merged**
